qortuba/Models/QortubaModel/Mboard.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qortuba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mboard
    {
        public int id { get; set; }
        public Nullable<int> sid { get; set; }
        public Nullable<int> empCode { get; set; }
        public string empName { get; set; }
        public string job { get; set; }
    }
}

qortuba/Models/QortubaModel/TSchools.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qortuba.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TSchools
    {

        [Key]
        public int SchoolID { get; set; }
        public Nullable<byte> area { get; set; }
        public Nullable<short> SectID { get; set; }
        public string School { get; set; }
        public Nullable<byte> LevelNo { get; set; }
        public Nullable<short> FDate { get; set; }
        public Nullable<byte> Build { get; set; }
        public Nullable<byte> kind_SCH { get; set; }
        public Nullable<byte> finalize { get; set; }
        public Nullable<byte> SchType { get; set; }
        public Nullable<int> dismiss { get; set; }
        public string EMail { get; set; }
        public Nullable<byte> Common { get; set; }
        public string Phone { get; set; }
        public Nullable<byte> desert { get; set; }
        public Nullable<int> SchoolID2 { get; set; }
        public Nullable<byte> created { get; set; }
        public Nullable<int> SchoolRID { get; set; }
        public Nullable<byte> repetID1 { get; set; }
        public Nullable<byte> repetID2 { get; set; }
        public Nullable<byte> addition { get; set; }
        public string DUbdat { get; set; }
        public Nullable<float> Distance { get; set; }
        public Nullable<byte> Mcde { get; set; }
        public Nullable<byte> Center { get; set; }
        public string City { get; set; }
        public string Liver { get; set; }
        public string street { get; set; }
        public Nullable<byte> Tuition { get; set; }
        public Nullable<byte> Door { get; set; }
        public Nullable<byte> CadE_door { get; set; }
        public Nullable<byte> Auhority { get; set; }
        public Nullable<byte> Tester { get; set; }
        public Nullable<byte> TsrPys { get; set; }
        public Nullable<byte> TsrEn { get; set; }
        public Nullable<byte> Tsertailor { get; set; }
        public Nullable<byte> Out { get; set; }
        public Nullable<byte> Backswept { get; set; }
        public string NearerSH1 { get; set; }
        public Nullable<short> Space1 { get; set; }
        public Nullable<byte> Varway1 { get; set; }
        public string NearerSH2 { get; set; }
        public Nullable<short> Space2 { get; set; }
        public Nullable<byte> Varway2 { get; set; }
        public string NearerSH3 { get; set; }
        public Nullable<short> Space3 { get; set; }
        public Nullable<byte> Varway3 { get; set; }
        public string FAx { get; set; }
        public string Site { get; set; }
        public Nullable<short> SchIDCom { get; set; }
        public Nullable<short> office { get; set; }
        public Nullable<short> Periority { get; set; }
        public Nullable<int> Strip { get; set; }
        public Nullable<int> StripPeriority { get; set; }
        public Nullable<byte> AfterNoon { get; set; }
        public Nullable<byte> Checked { get; set; }
        public string OldName { get; set; }
        public string OldCenter { get; set; }
        public Nullable<int> OldSchoolId { get; set; }
        public Nullable<byte> Rooms { get; set; }
        public Nullable<int> WezSchC { get; set; }
        public Nullable<int> BeforWezSchC { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public Nullable<int> circleEd { get; set; }
        public string location { get; set; }
		 public string locshot { get; set; }
        public Nullable<int> circleEd2 { get; set; }
        public Nullable<int> circleEd3 { get; set; }
        public Nullable<int> circleEd4 { get; set; }
        public string circleAll
        {
            get
            {

                return circleEd + "-" + circleEd2 + "-" + circleEd3 + "-" + circleEd4;
            }
        }
        public virtual T_area T_area { get; set; }
        public virtual T_Center T_Center { get; set; }
        public virtual TBuilding TBuilding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTable> TimeTable { get; set; }
        public virtual TLevel TLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassCompare> ClassCompare { get; set; }
        public virtual TSchoolsType TSchoolsType { get; set; }
        public virtual TSector TSector { get; set; }
        public virtual Tuition Tuition1 { get; set; }
    }
}

qortuba/Models/QortubaModel/TSchoolsType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qortuba.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TSchoolsType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSchoolsType()
        {
            this.TSchools = new HashSet<TSchools>();
        }
        [Key]
        public byte SchoolTyp { get; set; }
        public string SchoolsType { get; set; }
        public Nullable<int> BeforWez { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSchools> TSchools { get; set; }
    }
}

qortuba/Controllers/TSchoolsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using Newtonsoft.Json;
using qortuba.Models;
using ClosedXML.Excel;
using System.IO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using qortuba.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using qortuba.Models.Class;

namespace qortuba.Controllers
{

    public class TSchoolsController : Controller
    {

        private readonly ApplicationDbContext db;
      Models.Class.MyFunctions fun = new Models.Class.MyFunctions();
        public TSchoolsController(ApplicationDbContext Context)
        {
            db = Context;
        }

        // GET: TSchools
      //  [Authorize(Roles = "schoolShow")]
        public ActionResult Index()
        {
           

            List<School> list = new List<School>();
            DataTable dtable = fun.fireStoreProcedure("school");
            foreach (DataRow sdr in dtable.Rows)
            {
                School sch = new School();

                sch.SchoolID = sdr["SchoolID"].ToString();
                sch.SchoolName = sdr["SchoolName"].ToString();
                sch.circleAll = sdr["circleAll"].ToString();
                sch.name6 = sdr["name6"].ToString();
                sch.NameLevel = sdr["NameLevel"].ToString();
                sch.SchoolsType = sdr["SchoolsType"].ToString();
                sch.City = sdr["City"].ToString();
                sch.Bulding = sdr["Bulding"].ToString();
                sch.Tuition1 = sdr["Tuition1"].ToString();
                sch.Liver = sdr["Liver"].ToString();
                list.Add(sch);
            }
            ViewData["asd"] = dtable.Rows[0][3].ToString();
            ViewBag.adela = db.adela.Where(p => p.adServ == 2).ToList();
            return View(list);

        }

        // GET: TSchools/Details/5
     //   [Authorize(Roles = "schoolDetails")]
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                // return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TSchools tSchools = db.TSchools.Find(id);
            if (tSchools == null)
            {
                return NotFound();
            }
            vballModel(tSchools);
            return View(tSchools);


        }

        // GET: TSchools/Create
       // [Authorize(Roles = "schoolInser")]
        public ActionResult Create()
        {
            vball();

            return View();
        }

        // POST: TSchools/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
      //  [Authorize(Roles = "schoolInser")]
        public ActionResult Create(TSchools tSchools)
        {
            //try {

            var chk = db.TSchools.Where(t => t.SchoolID == tSchools.SchoolID).FirstOrDefault();
            if (chk != null)
            {

                ViewBag.error = "هذه المدرسة مسجلة من قبل";
                return View(tSchools);
            }
            if (ModelState.IsValid)
            {
                db.TSchools.Add(tSchools);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            vballModel(tSchools);
            return View(tSchools);


            //}
            //catch (Exception e)
            //{
            //    vballModel(tSchools);
            //    ViewBag.error = e.Message;
            //    return View(tSchools);
            //}
        }

        // GET: TSchools/Edit/5
        //[Authorize(Roles = "schoolUpdate")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                //  return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TSchools tSchools = db.TSchools.Find(id);
            if (tSchools == null)
            {
                return NotFound();
            }
            vballModel(tSchools);
            return View(tSchools);
        }

        // POST: TSchools/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
      //  [Authorize(Roles = "schoolUpdate")]
        public ActionResult Edit(TSchools tSchools)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    vballModel(tSchools);
                    db.Update(tSchools);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                vballModel(tSchools);
                return View(tSchools);


            }
            catch (Exception e)
            {
                vballModel(tSchools);
                ViewBag.error = "يوجد تداخل بين الرقم الوزارى المدخل مع رقم اخر .. تأكد من الرقم الرقم الوزارى";
                return View(tSchools);
            }
        }

        // GET: TSchools/Delete/5
     //   [Authorize(Roles = "schoolDelete")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TSchools tSchools = db.TSchools.Find(id);
            if (tSchools == null)
            {
                return NotFound();
            }
            vballModel(tSchools);
            return View(tSchools);
        }

        // POST: TSchools/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
   //     [Authorize(Roles = "schoolDelete")]
        public ActionResult DeleteConfirmed(int id)
        {

            TSchools tSchools = db.TSchools.Find(id);
            db.TSchools.Remove(tSchools);
            db.SaveChanges();
            return RedirectToAction("Index");


        }

        public void vball()
        {
            ViewBag.area = new SelectList(db.T_area, "IDNU", "name6");
            ViewBag.Center = new SelectList(db.T_Center, "ID", "Center1");
            ViewBag.Build = new SelectList(db.TBuilding, "BuildingID", "Bulding");
            ViewBag.LevelNo = new SelectList(db.TLevel, "LevelNo", "NameLevel");
            ViewBag.SchType = new SelectList(db.TSchoolsType, "SchoolTyp", "SchoolsType");
            ViewBag.SectID = new SelectList(db.TSector, "SectID", "Sector");
            ViewBag.Tuition = new SelectList(db.Tuition, "TuitionID", "Tuition1");
            ViewBag.finalize = new SelectList(db.T_yes_no, "on", "neme");
            ViewBag.Common = new SelectList(db.T_yes_no, "on", "neme");
            ViewBag.Backswept = new SelectList(db.T_yes_no, "on", "neme");
            ViewBag.created = new SelectList(db.T_yes_no, "on", "neme");
            ViewBag.Liver = new SelectList(db.HayNames, "HayName", "HayName");
            ViewBag.Out = new SelectList(db.T_yes_no, "on", "neme");
            ViewBag.CadE_door = new SelectList(db.TCadE_door, "CadE_ID", "CadE_door");
            ViewBag.AfterNoon = new SelectList(db.SchTypes, "SchType", "SchTypeName");
            ViewBag.desert = new SelectList(db.T_yes_no, "on", "neme");
            ViewBag.kind_SCH = new SelectList(db.T_yes_no, "on", "neme");
            ViewBag.Varway1 = new SelectList(db.T_Varway1, "Varway1ID", "Varway1");
            ViewBag.Varway2 = new SelectList(db.T_Varway1, "Varway1ID", "Varway1");
            ViewBag.Varway3 = new SelectList(db.T_Varway1, "Varway1ID", "Varway1");
            ViewBag.Rows = new SelectList(db.TLevel_Row, "Rows", "NameRow");

        }
        public void vballModel(TSchools tSchools)
        {

            ViewBag.area = new SelectList(db.T_area, "IDNU", "name6", tSchools.area);
            ViewBag.Center = new SelectList(db.T_Center, "ID", "Center1", tSchools.Center);
            ViewBag.Build = new SelectList(db.TBuilding, "BuildingID", "Bulding", tSchools.Build);
            ViewBag.LevelNo = new SelectList(db.TLevel, "LevelNo", "NameLevel", tSchools.LevelNo);
            ViewBag.SchType = new SelectList(db.TSchoolsType, "SchoolTyp", "SchoolsType", tSchools.SchType);
            ViewBag.SectID = new SelectList(db.TSector, "SectID", "Sector", tSchools.SectID);
            ViewBag.Tuition = new SelectList(db.Tuition, "TuitionID", "Tuition1", tSchools.Tuition);
            ViewBag.finalize = new SelectList(db.T_yes_no, "on", "neme", tSchools.finalize);
            ViewBag.Common = new SelectList(db.T_yes_no, "on", "neme", tSchools.Common);
            ViewBag.Backswept = new SelectList(db.T_yes_no, "on", "neme", tSchools.Backswept);
            ViewBag.created = new SelectList(db.T_yes_no, "on", "neme", tSchools.created);
            ViewBag.Liver = new SelectList(db.HayNames, "HayName", "HayName", tSchools.Liver);
            ViewBag.Out = new SelectList(db.T_yes_no, "on", "neme", tSchools.Out);
            ViewBag.CadE_door = new SelectList(db.TCadE_door, "CadE_ID", "CadE_door", tSchools.CadE_door);
            ViewBag.AfterNoon = new SelectList(db.SchTypes, "SchType", "SchTypeName", tSchools.AfterNoon);
            ViewBag.desert = new SelectList(db.T_yes_no, "on", "neme", tSchools.desert);
            ViewBag.kind_SCH = new SelectList(db.T_yes_no, "on", "neme", tSchools.kind_SCH);
            ViewBag.Varway1 = new SelectList(db.T_Varway1, "Varway1ID", "Varway1", tSchools.Varway1);
            ViewBag.Varway2 = new SelectList(db.T_Varway1, "Varway1ID", "Varway1", tSchools.Varway2);
            ViewBag.Varway3 = new SelectList(db.T_Varway1, "Varway1ID", "Varway1", tSchools.Varway3);
            ViewBag.Rows1 = new SelectList(db.TLevel_Row.Where(t => t.LevelNo == tSchools.LevelNo), "Rows", "NameRow");

qortuba/Views/TSchools/Mboard.cshtml
@model IEnumerable<qortuba.Models.Mboard>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}



<div class="row">
    @using (Html.BeginForm("CeareMboard", "TSchools", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <input type="hidden" name="sid" id="sid" value="@ViewBag.sid" />
        <div class="col-sm-2">
            <p>تحديد المعلم</p>
        </div>
        <div class="col-sm-3">
            @Html.DropDownList("empName", null, "--من فضلك اختار--", htmlAttributes: new { @class = "form-control", required = "required" })
        </div>
        <div class="col-sm-2">
            <p>تحديد العمل</p>
        </div>
        <div class="col-sm-2">
            @Html.DropDownList("job", null, "--من فضلك اختار--", htmlAttributes: new { @class = "form-control", required = "required" })
        </div>
        <div class="col-sm-2">
            <input type="submit" value="إضافة" class="btn btn-success" />
        </div>
    }
</div>



<div class="page-container">

    <div class="main-container">

        <div class="main-content">

            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading clearfix">
                            <h3 class="panel-title"> مجلس إدارة المدرسة</h3>
                            <ul class="panel-tool-options">
                                <li><a data-rel="collapse" href="#"><i class="icon-down-open"></i></a></li>
                                <li><a data-rel="reload" href="#"><i class="icon-arrows-ccw"></i></a></li>
                                <li><a data-rel="close" href="#"><i class="icon-cancel"></i></a></li>
                            </ul>
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>
                                        <tr>
                                         
                                            <th style="background-color:#c8f1c3">كود</th>
                                            <th style="background-color:#c8f1c3">اسم المعلم</th>
                                            <th style="background-color:#c8f1c3"> العمل</th>
                                            <th style="background-color:#c8f1c3"> </th>

                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (var item in Model)
                                        {


                                        <tr class="gradeX">
                                            <td>@item.id</td>
                                            <td>@item.empName</td>
                                            <td>@item.job</td>


                                            <td>@Html.ActionLink(" حذف", "Delete", new { id = item.id }, new { @class = "btn btn-danger" })</td>

                                        </tr>
                                        }

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<script src="~/newStyle/js/jquery.min.js"></script>
<script src="~/newStyle/js/bootstrap.min.js"></script>
<script src="~/newStyle/js/plugins/metismenu/jquery.metisMenu.js"></script>
<script src="~/newStyle/js/plugins/blockui-master/jquery-ui.js"></script>
<script src="~/newStyle/js/plugins/blockui-master/jquery.blockUI.js"></script>
<script src="~/newStyle/js/functions.js"></script>
<script src="~/newStyle/js/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/newStyle/js/plugins/datatables/dataTables.bootstrap.min.js"></script>
<script src="~/newStyle/js/plugins/datatables/extensions/Buttons/js/dataTables.buttons.min.js"></script>
<script src="~/newStyle/js/plugins/datatables/jszip.min.js"></script>
<script src="~/newStyle/js/plugins/datatables/pdfmake.min.js"></script>
<script src="~/newStyle/js/plugins/datatables/vfs_fonts.js"></script>
<script src="~/newStyle/js/plugins/datatables/extensions/Buttons/js/buttons.html5.js"></script>
<script src="~/newStyle/js/plugins/datatables/extensions/Buttons/js/buttons.colVis.js"></script>
<script>
    $(document).ready(function () {
        $('.dataTables-example').DataTable({
            dom: '<"html5buttons" B>lTfgitp',
            buttons: [
                {
                    extend: 'copyHtml5',
                    exportOptions: {
                        columns: [0, ':visible']
                    }
                },
                {
                    extend: 'excelHtml5',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'pdfHtml5',
                    exportOptions: {
                        columns: [0, 1, 2, 3, 4]
                    }
                },
                'colvis'
            ]
        });
    });
</script>

@section scripts{
    <script>



        $(".table tbody").on('click', '.btn-danger', function (e) {
            e.preventDefault();

            var currentRow = $(this).closest('tr');
            var id = currentRow.find("td:eq(0)").text();

            if (id != null) {
                if (confirm('هل انت متأكد من الحذف ؟')) {
                    $.ajax({
                        url: "/TSchools/DeleteMboard?id=" + id,
                        type: "POST",

                        success: function (data) {

                            window.location.reload();

                        },
                        error: function () {
                            $("#error").html("مشكلة فى الحفظ");
                            $("#myModal").modal('show');
                        }
                    });
                }
            }

        })

    </script>

}

qortuba/Views/TSchools/MboardManager.cshtml
@model IEnumerable<qortuba.Models.Mboard>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}


<div class="titleBody">
    <label> مجلس إدارة المدرسة</label>

</div>
<div class="panel panel-info">
    <div class="panel-heading" style="background-color:#efc66c;font-size:16px;">
        الادلة والتعاميم
    </div>
    <div class="panel-body">
        <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                تحميل الادلة والتعاميم
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" dir="rtl">
                @foreach (var de in ViewBag.adela)
                {
                    string path = de.id + de.adFile;
                    string dname = de.adName + de.adFile;
                    <li><a href="../../Upload/Emp/@path" download="@dname">@de.adName</a></li>
                }


            </ul>
        </div>
    </div>
</div>

<div class="row">
    @using (Html.BeginForm("CeareMboardManager", "TSchools", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <input type="hidden" name="sid" id="sid" value="@ViewBag.sid" />
        <div class="col-sm-2">
            <p>تحديد المعلم</p>
        </div>
        <div class="col-sm-3">
            @Html.DropDownList("empName", null, "--من فضلك اختار--", htmlAttributes: new { @class = "form-control", required = "required" })
        </div>
        <div class="col-sm-2">
            <p>تحديد العمل</p>
        </div>
        <div class="col-sm-2">
            @Html.DropDownList("job", null, "--من فضلك اختار--", htmlAttributes: new { @class = "form-control", required = "required" })
        </div>
        <div class="col-sm-2">
            <input type="submit" value="إضافة" class="btn btn-success" />
        </div>
    }
</div>





<div class="page-container">

    <div class="main-container">

        <div class="main-content">

            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading clearfix">
                            <h3 class="panel-title">العجز والزيادة </h3>
                            <ul class="panel-tool-options">
                                <li><a data-rel="collapse" href="#"><i class="icon-down-open"></i></a></li>
                                <li><a data-rel="reload" href="#"><i class="icon-arrows-ccw"></i></a></li>
                                <li><a data-rel="close" href="#"><i class="icon-cancel"></i></a></li>
                            </ul>
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>
                                        <tr>


                                           
                                            <th style="background-color:#c8f1c3">  كود</th>
                                            <th style="background-color:#c8f1c3"> اسم المعلم </th>
                                            <th style="background-color:#c8f1c3">  العمل</th>



                                            <th style="background-color:#c8f1c3"> </th>

                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (var item in Model)
                                        {

                 
                                        <tr class="gradeX">
                                            <td>@item.id</td>
                                            <td>@item.empName</td>
                                            <td>@item.job</td>


                                            <td>@Html.ActionLink("  حذف ", "Delete", new { id = item.id }, new { @class = "btn btn-danger" })</td>

                                        </tr>
                                        }

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<script src="~/newStyle/js/jquery.min.js"></script>
<script src="~/newStyle/js/bootstrap.min.js"></script>
<script src="~/newStyle/js/plugins/metismenu/jquery.metisMenu.js"></script>
<script src="~/newStyle/js/plugins/blockui-master/jquery-ui.js"></script>
<script src="~/newStyle/js/plugins/blockui-master/jquery.blockUI.js"></script>
<script src="~/newStyle/js/functions.js"></script>
<script src="~/newStyle/js/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/newStyle/js/plugins/datatables/dataTables.bootstrap.min.js"></script>
<script src="~/newStyle/js/plugins/datatables/extensions/Buttons/js/dataTables.buttons.min.js"></script>
<script src="~/newStyle/js/plugins/datatables/jszip.min.js"></script>
<script src="~/newStyle/js/plugins/datatables/pdfmake.min.js"></script>
<script src="~/newStyle/js/plugins/datatables/vfs_fonts.js"></script>
<script src="~/newStyle/js/plugins/datatables/extensions/Buttons/js/buttons.html5.js"></script>
<script src="~/newStyle/js/plugins/datatables/extensions/Buttons/js/buttons.colVis.js"></script>



@section scripts{
    <script>



        $(".table tbody").on('click', '.btn-danger', function (e) {
            e.preventDefault();

            var currentRow = $(this).closest('tr');
            var id = currentRow.find("td:eq(0)").text();

            if (id != null) {
                if (confirm('هل انت متأكد من الحذف ؟')) {
                    $.ajax({
                        url: "/TSchools/DeleteMboard?id=" + id,
                        type: "POST",

                        success: function (data) {

                            window.location.reload();

                        },
                        error: function () {
                            $("#error").html("مشكلة فى الحفظ");
                            $("#myModal").modal('show');
                        }
                    });
                }
            }

        })

    </script>

}