qortuba/Controllers/AcceptanceController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using qortuba.Data;
using qortuba.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace qortuba.Controllers
{
    public class AcceptanceController : Controller
    {
        private readonly ApplicationDbContext db;
       // securityParametar sc = new securityParametar();
        public AcceptanceController(ApplicationDbContext Context)
        {
            db = Context;
        }
        public ActionResult Index()
        {
            ViewBag.adela = db.adela.Where(p => p.adServ == 6).ToList();
            return View();
        }

        public ActionResult watingList(int sid, int srow, string sname, string rowName)
        {
            if (sid > 0 && srow > 0)
            {
                List<studentsWait> st = new List<studentsWait>();
                var dd = (from ts in db.studentsWait
                          join sc in db.TSchools on ts.oldSchid equals sc.SchoolID into gj
                          from sc in gj.DefaultIfEmpty()

                          where ts.schid == sid && ts.srow == srow && ts.Sstate != 1
                          orderby (ts.id)
                          select new
                          {
                              id = ts.id,
                              sid = ts.sid,
                              stname = ts.sname1 + " " + ts.sname2 + " " + ts.sname3 + " " + ts.snname4,
                              fid = ts.fid,
                              ftname = ts.fname1 + " " + ts.fname2 + " " + ts.fname3 + " " + ts.fname4,
                              oldsch = sc.School,
                              stuts1 = ts.Sstate == 1 ? "قبول نهائى" : ts.Sstate == 2 ? "يلزم مراجعة اللجنة المركزية " : ts.Sstate == 3 ? "لا يوجد مقعد شاغر" : ts.Sstate == 1002 ? "يوجد ملاحظات على نظامية التسجيل" : "إنتظار",
                              srow = ts.rowName,
                              mob = ts.mob


                          });
                foreach (var lp in dd)
                {
                    studentsWait sd = new studentsWait();
                    sd.id = lp.id;
                    sd.sname1 = lp.stname;
                    sd.fname1 = lp.ftname;
                    sd.sid = lp.sid;
                    sd.fid = lp.fid;
                    sd.sname = lp.oldsch; // old school
                    sd.sname2 = lp.stuts1; //status
                    sd.rowName = lp.srow;
                    sd.mob = lp.mob;
                    st.Add(sd);
                }

                ViewBag.sname = sname;
                ViewBag.srow = rowName;
                return View(st);

            }
            else
            {
                return View("Index");
            }

        }
        public ActionResult RecordStudent(students students)
        {


            return View("RecordStudent", students);
        }

        public ActionResult RecordStudentWait(studentsWait students)
        {


            return View("RecordStudentWait", students);
        }

        public ActionResult AddStudent(IFormFile homeCert, IFormFile familyCert, IFormFile oldCert, IFormFile care, IFormFile transfare, students students)
        {


            //if (!this.IsCaptchaValid(""))

            //{

            //    @ViewBag.error = "خطأ.. الرجاء مراجعة البيانات";




            //    return View("RecordStudent", students);
            //}
            //else
            //{

            int ss = db.students.Where(p => p.sid == students.sid).Count();
            string[] ex = { ".png", ".jpg", ".jpeg", ".pdf" };

            if (ss >= 1)
            {
                @ViewBag.error = "خطأ.. الطالب مسجل من قبل";
                return View("RecordStudent", students);

            }
            else
            {
                string homec = "";
                string familyC = "";
                string oldC = "";
                string carC = "";
                string tras = "";







                if (homeCert != null && homeCert.Length > 0)
                {

                    string extension = Path.GetExtension(homeCert.FileName);
                    bool a = Array.Exists(ex, element => element == extension);
                    long sz = homeCert.Length;
                    if (a == true && sz <= 16777216)
                    {
                        if (!Directory.Exists(Path.GetFileName("~/Upload/homeCert/" + students.schid + "")))
                        {

                            var FullPath = Path.Combine(Path.GetFileName("~/Upload/homeCert/" + students.schid + "/" + students.sid + extension));
                            homec = students.sid + extension;
                            using (var fileSteam = new FileStream(FullPath, FileMode.Create))
                            {
                                homeCert.CopyToAsync(fileSteam);
                            }
                        }
                        else
                        {

                            var FullPath = Path.Combine(Path.GetFileName("~/Upload/homeCert/" + students.schid + "/" + students.sid + extension));
                            homec = students.sid + extension;
                            using (var fileSteam = new FileStream(FullPath, FileMode.Create))
                            {
                                homeCert.CopyToAsync(fileSteam);
                            }


                        }
                    }
                }








                if (familyCert != null && familyCert.Length > 0)
                {

                    string extension = Path.GetExtension(familyCert.FileName);
                    bool a = Array.Exists(ex, element => element == extension);
                    long sz = familyCert.Length;
                    if (a == true && sz <= 16777216)
                    {

                        if (!Directory.Exists(Path.GetFileName("~/Upload/familyCert/" + students.schid + "")))
                        {

                            Directory.CreateDirectory(Path.GetFileName("~/Upload/familyCert/" + students.schid + ""));
                            var FullPath = Path.Combine(Path.GetFileName("~/Upload/familyCert/" + students.schid + "/" + students.sid + extension));
                            familyC = students.sid + extension;


                            using (var fileSteam = new FileStream(FullPath, FileMode.Create))
                            {
                                familyCert.CopyToAsync(fileSteam);
                            }

                        }
                        else
                        {

                            var FullPath = Path.Combine(Path.GetFileName("~/Upload/familyCert/" + students.schid + "/" + students.sid + extension));
                            familyC = students.sid + extension;
                            using (var fileSteam = new FileStream(FullPath, FileMode.Create))
                            {
                                familyCert.CopyToAsync(fileSteam);
                            }
                        }
                    }
                }

                if (oldCert != null && oldCert.Length > 0)
                {

                    string extension = Path.GetExtension(oldCert.FileName);
                    bool a = Array.Exists(ex, element => element == extension);
                    long sz = oldCert.Length;
                    if (a == true && sz <= 16777216)
                    {

                        if (!Directory.Exists(Path.GetFileName("~/Upload/oldCert/" + students.schid + "")))
                        {

                            Directory.CreateDirectory(Path.GetFileName("~/Upload/oldCert/" + students.schid + ""));
                            var FullPath = Path.Combine(Path.GetFileName("~/Upload/oldCert/" + students.schid + "/" + students.sid + extension));
                            oldC = students.sid + extension;
                            using (var fileSteam = new FileStream(FullPath, FileMode.Create))
                            {
                                oldCert.CopyToAsync(fileSteam);
                            }
                        }
                        else
                        {

                            var FullPath = Path.Combine(Path.GetFileName("~/Upload/oldCert/" + students.schid + "/" + students.sid + extension));
                            oldC = students.sid + extension;
                            using (var fileSteam = new FileStream(FullPath, FileMode.Create))
                            {
                                oldCert.CopyToAsync(fileSteam);
                            }
                        }
                    }
                }

                if (care != null && care.Length > 0)
                {

                    string extension = Path.GetExtension(care.FileName);
                    bool a = Array.Exists(ex, element => element == extension);
                    long sz = care.Length;
                    if (a == true && sz <= 16777216)
                    {

                        if (!Directory.Exists(Path.GetFileName("~/Upload/care/" + students.schid + "")))
                        {

                            Directory.CreateDirectory(Path.GetFileName("~/Upload/care/" + students.schid + ""));
                            var FullPath = Path.Combine(Path.GetFileName("~/Upload/care/" + students.schid + "/" + students.sid + extension));
                            carC = students.sid + extension;
                            using (var fileSteam = new FileStream(FullPath, FileMode.Create))
                            {
                                care.CopyToAsync(fileSteam);
                            }
                        }
                        else
                        {

qortuba/Views/Acceptance/AcceptanceMain.cshtml
@{
    ViewBag.Title = "القبول";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
<style>
    .ic{
        width:180px;
        height:150px;
        margin:90px;
        padding-top:55px;
    }
    .ac{
        color:#fff;
      
    }
    .txt{
        font-weight: bold;
    }
</style>
<div>
    <table>
        <tr>
            <td>
                <a class="btn btn-success  ic" href="/TSchools/AcceptanceTrue?id=@ViewBag.id">
                    
                        <span class="txt">قائمة الطلاب المقبولين</span><span> <i class="fa fa-check fa-fw " style="font-size:20px;color: brown;"></i></span>
                   
                </a>
            </td>
            <td>
                <a class="btn btn-primary  ic" href="/TSchools/AcceptanceState?id=@ViewBag.id">

                    <span class="txt"> طلبات القبول</span><span> <i class="fa fa-edit fa-fw text-success" style="font-size:20px;color: yellow;"></i></span>

                </a>

            </td>
            <td>
            <td>
                <a class="btn btn-warning  ic" href="/TSchools/AcceptanceWating?id=@ViewBag.id">

                    <span class="txt"> طلبات الانتظار</span><span> <i class="fa fa-tasks fa-fw text-success" style="font-size:20px;"></i></span>

                </a>
                
            </td>
        </tr>
    </table>
</div>

qortuba/Views/Acceptance/AcceptanceMainM.cshtml
@{
    ViewBag.Title = "القبول";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
<style>
    .ic {
        width: 180px;
        height: 150px;
        margin: 90px;
        padding-top: 55px;
    }

    .ac {
        color: #fff;
    }

    .txt {
        font-weight: bold;
    }
</style>
<div>
    <table>
        <tr>
            <td>
                <a class="btn btn-success  ic" href="/TSchools/AcceptanceTrue?id=@ViewBag.id">

                    <span class="txt">قائمة الطلاب المقبولين</span><span> <i class="fa fa-check fa-fw " style="font-size:20px;color: brown;"></i></span>

                </a>
            </td>
            <td>
                <a class="btn btn-primary  ic" href="/TSchools/AcceptanceState?id=@ViewBag.id">

                    <span class="txt"> طلبات القبول</span><span> <i class="fa fa-edit fa-fw text-success" style="font-size:20px;color: yellow;"></i></span>

                </a>

            </td>
            <td>
            <td>
                <a class="btn btn-warning  ic" href="/TSchools/AcceptanceWating?id=@ViewBag.id">

                    <span class="txt"> طلبات الانتظار</span><span> <i class="fa fa-tasks fa-fw text-success" style="font-size:20px;"></i></span>

                </a>

            </td>
        </tr>
    </table>
</div>

qortuba/Views/Acceptance/RecordStudent.cshtml
@model qortuba.Models.students
@using qortuba.Models
@using qortuba.Data
@inject ApplicationDbContext db

@*@using CaptchaMvc.HtmlHelpers*@

@{
    ViewBag.Title = "تسجيل طلب";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<style>

    #trs {
        visibility: hidden;
    }

    .selectD {
        height: 30px;
        width: 100%;
        border-radius: 5px;
        box-shadow: inset 0 0 5px 2px #4cc33d;
    }
</style>
<div class="titleBody">
    <label class="lbl-nav"><a href="">تسجيل طالب</a></label>

</div>
@using (Html.BeginForm("AddStudent", "Acceptance", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()


    <div class="form-inline ">

        <hr />
        <label class="text-danger">@ViewBag.error</label>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div>
            @Html.ValidationMessageFor(model => model.sname1, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.sid, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.sname1, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.sname2, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.sname3, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.fname4, "", new { @class = "text-danger" })

            @Html.ValidationMessageFor(model => model.fname1, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.fname2, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.fname3, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.fname4, "", new { @class = "text-danger" })

            @Html.ValidationMessageFor(model => model.sid, "", new { @class = "text-danger" })


            @Html.ValidationMessageFor(model => model.familyCert, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.homeCert, "", new { @class = "text-danger" })

        </div>
        @*  first row*@
        <div class="panel panel-success">
            <div class="panel-heading">بيانات الطلب</div>
            <div class="panel-body">
                <table class="table">
                    <tr>
                        <td>
                            <span style="font-weight: bold;">اسم المدرسة /</span>
                            <span style="font-weight: bold;color:blue;">@Model.sname</span>
                        </td>
                        <td>
                            <span style="font-weight: bold;">الصف /</span>
                            <span style="font-weight: bold;color:blue;">@Model.rowName</span>
                        </td>
                        <td>
                            <p style="font-weight: bold;display:inline-block;">حالة الطالب</p>
                            <select id="acceptS" name="acceptS" class="selectD " style="width: 150px;">
                                <option value="1">منقول</option>
                                <option value="2">مستجد</option>
                                <option value="3">محول</option>
                            </select>

                        </td>
                    </tr>
                </table>
                <input id="schid" name="schid" value="@Model.schid" type="hidden" />
                <input id="srow" name="srow" value="@Model.srow" type="hidden" />
                <input id="sname" name="sname" value="@Model.sname" type="hidden" />
                <input id="rowName" name="rowName" value="@Model.rowName" type="hidden" />

            </div>
        </div>

        <div class="panel panel-primary">
            <div class="panel-heading">بيانات الطالب</div>
            <div class="panel-body">
                <div class="form-group row col-md-12 ">
                    @Html.Label("", "اسم الطالب", htmlAttributes: new { @class = "col-sm-2 " })
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.sname1, new { htmlAttributes = new { @class = "form-control nam mr", placeholder = "الاسم الاول", required = "required" } })
                        @Html.EditorFor(model => model.sname2, new { htmlAttributes = new { @class = "form-control nam", placeholder = "الاسم الثانى", required = "required" } })
                        @Html.EditorFor(model => model.sname3, new { htmlAttributes = new { @class = "form-control nam", placeholder = "الاسم الثالث", required = "required" } })
                        @Html.EditorFor(model => model.fname4, new { htmlAttributes = new { @class = "form-control nam", placeholder = "اسم العائلة", required = "required" } })
                    </div>
                </div>
                <div class="form-group row col-md-4">
                    @Html.Label("", "السجل المدنى للطالب", htmlAttributes: new { @class = "col-sm-5 " })
                    <div class="col-sm-7">
                        @Html.EditorFor(model => model.sid, new { htmlAttributes = new { @class = "form-control", required = "required", minlength = "10", maxlength = "10" } })

                    </div>

                </div>
                <div class="form-group row col-md-8 ">
                    @Html.Label("", "المدرسة السابقة", htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        <select id="oldSchid" name="oldSchid" class="form-control">
                            @{
                                <option value="">-- من فضلك إختار --</option>

                                var vl = db.TSchools;
                                foreach (var sd in vl)
                                {
                                    <option value="@sd.SchoolID">@sd.School</option>
                                }
                            }

                        </select>
                    </div>
                </div>

                <div class="form-group row col-md-4 ">
                    @Html.Label("", "الجنسية", htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        <select id="nat" name="nat" class="form-control">
                            @{
                                <option value="">-- من فضلك إختار --</option>

                                    var vl1 = db.TNationality;
                                    foreach (var sd in vl1)
                                    {
                                        <option value="@sd.NatID">@sd.Nationality</option>
                                    }
                            }

                        </select>
                    </div>
                </div>

                <div class="form-group row col-md-8 ">
                    @Html.Label("", "الشهادة السابقة", htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        <input id="oldCert" name="oldCert" type="file" class="form-control" required />
                    </div>
                </div>

            </div>
        </div>


        <div class="panel panel-info">
            <div class="panel-heading">بيانات ولى الامر</div>
            <div class="panel-body">
                <div class="form-group row col-md-12 ">
                    @Html.Label("", "اسم ولى الامر", htmlAttributes: new { @class = "col-sm-2 " })
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.fname1, new { htmlAttributes = new { @class = "form-control nam mr", placeholder = "الاسم الاول", required = "required" } })
                        @Html.EditorFor(model => model.fname2, new { htmlAttributes = new { @class = "form-control nam", placeholder = "الاسم الثانى", required = "required" } })
                        @Html.EditorFor(model => model.fname3, new { htmlAttributes = new { @class = "form-control nam", placeholder = "الاسم الثالث", required = "required" } })
                        @Html.EditorFor(model => model.fname4, new { htmlAttributes = new { @class = "form-control nam", placeholder = "اسم العائلة", required = "required" } })

                    </div>
                </div>
                <div class="form-group row col-md-4">
                    @Html.Label("", "السجل المدنى لولى الامر", htmlAttributes: new { @class = "col-sm-5 " })
                    <div class="col-sm-7">
                        @Html.EditorFor(model => model.fid, new { htmlAttributes = new { @class = "form-control", required = "required", minlength = "10", maxlength = "10" } })

                    </div>

                </div>
                <div class="form-group row col-md-8 ">
                    @Html.Label("", "الجوال", htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.mob, new { htmlAttributes = new { @class = "form-control", required = "required", placeholder = "966550000000", maxlength = "12", minlength = "12" } })

                    </div>
                </div>

                @*  2 row*@

                <div class="form-group row col-md-6">
                    @Html.Label("", "سجل الاسرة", htmlAttributes: new { @class = "col-sm-2 col-form-label", required = "required" })
                    <div class="col-sm-10">
                        <input id="familyCert" name="familyCert" type="file" class="form-control" required />

                    </div>
                </div>

                <div class="form-group row col-md-6">
                    @Html.Label("", "إثبات سكن", htmlAttributes: new { @class = "col-sm-2 col-form-label", required = "required" })
                    <div class="col-sm-10">
                        <input id="homeCert" name="homeCert" type="file" class="form-control" required />

                    </div>
                </div>

                <div class="form-group row col-md-6 ">
                    @Html.Label("", "إثبات الرعاية", htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        <input id="care" name="care" type="file" class="form-control" />
                    </div>
                </div>
                <div class="form-group row col-md-6 " id="trs">
                    @Html.Label("", "نموذج التحويل", htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        <input id="transfare" name="transfare" type="file" class="form-control" />
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-warning">
            <div class="panel-heading" style="background-color:#f2e274;">رمز التأكيد </div>
            <div class="panel-body">

                @*  @Html.Captcha(3)*@


            </div>
        </div>



        <div class="form-inline">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="إرسال" class="btn btn-success" />
                @Html.ActionLink("عودة", "Index", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>





}
@section scripts{
    <script>

        document.addEventListener("DOMContentLoaded", function () {
            var elements = document.getElementsByTagName("INPUT");
            for (var i = 0; i < elements.length; i++) {
                elements[i].oninvalid = function (e) {
                    e.target.setCustomValidity("");
                    if (!e.target.validity.valid) {
                        e.target.setCustomValidity("لا يجوز ترك الحقل خالى");
                    }
                };
                elements[i].oninput = function (e) {
                    e.target.setCustomValidity("");
                };
            }
        })

        $(function () {
            $('input[type=file]').change(function () {
                var val = $(this).val().toLowerCase(),
                    regex = new RegExp("(.*?)\.(png|jpg|jpeg|pdf)$");

                if (!(regex.test(val))) {
                    $(this).val('');
                    alert('من فضلك يجب ان يكون امتداد الملف (png|jpg|jpeg|pdf)');
                }
                if (this.files[0].size > 16777216) {
                    alert("يجب ان يكون حجم الملف اقل من 16 ميجا");
                }
            });
            $('#selectD').change(function () {
                var vl = $(this).val();
                if (vl == 3) {
                    $('#trs').css('visibility', 'visible');
                } else {
                    $('#trs').css('visibility', 'hidden');
                }

            });

        });

 function idMsg(textbox) {

    if (textbox.value == '') {
        textbox.setCustomValidity('الحقل خاالى ');
    }
    else if (textbox.value.lenght != 10) {
        textbox.setCustomValidity('رقم السجل المدنى مكون من 10 ارقام ');
    }
    else {
        textbox.setCustomValidity('');
    }
    return true;
}

    </script>

}

qortuba/Views/Acceptance/SuccessSutudent.cshtml
@model qortuba.Models.students
@{
    ViewBag.Title = "SuccessSutudent";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<div class="titleBody">
    <label class="lbl-nav"><a href="">تم تسجيل الطلب بنجاح</a></label>

</div>
<div class="panel panel-success">
    <div class="panel-heading">
        <span style="font-size:18px;"> تم إرسال طلبكم بنجاح</span>
        <img src="~/images/res/1.png" width="60" height="60" />
    </div>
    <div class="panel-body">
        
        <div>
            <p style="font-size:18px;text-align:center;
    font-weight: bold;">رقم الطلب / <span style="font-size:18px;color:blue;">@Model.id</span></p>

            
        </div>
        <div>
            <p style="font-size:16px;text-align:center;width:350px;color:#df2323;font-weight:bold;">الرجاء الحضور الى المدرسة بالاوراق المطلوبة فى موعد اقصاة 72 ساعة من ارسال الطلب</p>
        </div>

    </div>
</div>

qortuba/Views/Acceptance/SuccessSutudentWait.cshtml
@model qortuba.Models.studentsWait
@{
    ViewBag.Title = "SuccessSutudent";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<div class="titleBody">
    <label class="lbl-nav"><a href="">تم تسجيل طلب إنتظار بنجاح</a></label>

</div>
<div class="panel panel-success">
    <div class="panel-heading">
        <span style="font-size:18px;"> تم إرسال طلبكم بنجاح</span>
        <img src="~/images/res/1.png" width="60" height="60" />
    </div>
    <div class="panel-body">

        <div>
            <p style="font-size:18px;text-align:center;
    font-weight: bold;">رقم الطلب  / <span style="font-size:18px;color:blue;">@Model.id</span></p>


</div>


</div>
</div>