qortuba/Models/Class/TeachReport.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace qortuba.Models
{
    public class TeachReport
    {
        public string id { get; set; }
        public string t_id { get; set; }
        public int day_id { get; set; }
        public string dayname { get; set; }
        public string period_id { get; set; }
        public string class_id { get; set; }
        public string Subject { get; set; }
        public int daynum { get; set; }

        public int pernum { get; set; }

    }
}

qortuba/Models/ModeView/TimeTableView.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace qortuba.Models.ModeView
{
    public class TimeTableView
    {
        public TimeTable timeTable { get; set; }
        public supervision superVision { get; set; }
        public day_s day_S { get; set; }
        public IEnumerable<periods> periods { get; set; }
        public IEnumerable<TCLassRow> tCLassRows { get; set; }
        public IEnumerable<TSubject> tSubject { get; set; }
        public IEnumerable<TImployees> tImployees { get; set; }
        public List<SelectListItem> vMethods { get; set; }
        public IEnumerable<TeachReport> teachReports { get; set; }
    }
}

qortuba/Models/QortubaModel/TimeTable.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qortuba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeTable()
        {
            this.day_s = new HashSet<day_s>();
            this.periods = new HashSet<periods>();
            this.supervision = new HashSet<supervision>();
        }
    
        public int id { get; set; }
        public Nullable<int> sch_id { get; set; }
        public Nullable<System.DateTime> cr_date { get; set; }
        public string cr_id { get; set; }
        public Nullable<System.DateTime> up_date { get; set; }
        public Nullable<int> up_id { get; set; }
        public Nullable<int> day_num { get; set; }
        public Nullable<int> per_num { get; set; }
        public Nullable<int> caseA { get; set; }
        public Nullable<int> viewM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<day_s> day_s { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<periods> periods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supervision> supervision { get; set; }
        public virtual viewMethod viewMethod { get; set; }
    }
}

qortuba/Controllers/TimeTableController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Globalization;
using System.Linq;
using System.Net;
using qortuba.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using qortuba.Data;
using System.IO;
using Microsoft.AspNetCore.Mvc.Rendering;
using qortuba.Models.ModeView;
using Microsoft.EntityFrameworkCore;
using Rotativa.AspNetCore;
using Microsoft.AspNetCore.Hosting;

namespace qortuba.Controllers
{

    public class TimeTableController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly IHostingEnvironment _HostEnvironment;
        Models.Class.MyFunctions fun = new Models.Class.MyFunctions();
        public TimeTableController(ApplicationDbContext Context, IHostingEnvironment HostEnvironment)
        {
            db = Context;
            _HostEnvironment = HostEnvironment;
        }

        // GET: TimeTable
      //  [Authorize(Roles = "TimeTable")]
        public ActionResult Index()
        {
            List<School> list = new List<School>();
            DataTable dtable = fun.fireStoreProcedure("SchoolTable");
            foreach (DataRow sdr in dtable.Rows)
            {
                School sch = new School();

                sch.SchoolID = sdr["SchoolID"].ToString();
                sch.SchoolName = sdr["SchoolName"].ToString();
                sch.circleAll = sdr["circleAll"].ToString();
                sch.name6 = sdr["name6"].ToString();
                sch.NameLevel = sdr["NameLevel"].ToString();
                sch.SchoolsType = sdr["SchoolsType"].ToString();
                sch.City = sdr["City"].ToString();
                sch.Tuition1 = sdr["Tuition1"].ToString();
                sch.Liver = sdr["Liver"].ToString();
                list.Add(sch);
            }
            ViewBag.adela = db.adela.Where(p => p.adServ == 3).ToList();
            return View(list);

        }

        public ActionResult ShowTables(int id)
        {
            DataTable dt = fun.fireStoreProcedure3("TimeTableAuto", id.ToString(), "5", "8");
            List<DesForTime> ListDf = new List<DesForTime>();
            foreach (DataRow dr in dt.Rows)
            {
                DesForTime dsf = new DesForTime();
                dsf.empId = dr["empId"].ToString();
                dsf.Teacher = dr["TEACHAR"].ToString();
                dsf.suID = dr["suID"].ToString();
                dsf.subj = dr["subj"].ToString();
                dsf.stat = dr["stat"].ToString();
                dsf.Reduce = dr["Reduce"].ToString();
                dsf.def = dr["def"].ToString();
                dsf.addclass = dr["addClass"].ToString();
                dsf.addSub = dr["addSubClass"].ToString();
                ListDf.Add(dsf);
            }
            DataTable dt1 = fun.fireStoreProcedure1("DesIntable", id.ToString());

            List<DesForTime> ListDf1 = new List<DesForTime>();
            foreach (DataRow dr1 in dt1.Rows)
            {
                DesForTime dsf1 = new DesForTime();
                dsf1.empId = dr1["ID"].ToString();
                dsf1.subj = dr1["SUB"].ToString();
                dsf1.stat = dr1["dess"].ToString();
                ListDf1.Add(dsf1);
            }


            CultureInfo cultures = CultureInfo.CreateSpecificCulture("ar-SA");
            Models.ModeView.Schools ischools = new Models.ModeView.Schools();

            ischools.tSchools = db.TSchools.Include(t => t.T_area).Include(t => t.T_Center).Include(t => t.TBuilding).Include(t => t.TLevel).Include(t => t.TSchoolsType).Include(t => t.TSector).Include(t => t.Tuition1).Where(t => t.SchoolID == id).FirstOrDefault();
            ischools.tCLassRow = db.TCLassRow.Include(t => t.TLevel_Row).Where(t => t.SchoolID == id).ToList().OrderBy(p => p.Rows);
            ischools.ttimetable = db.TimeTable.Where(t => t.sch_id == id).ToList();
            ischools.desForTime = ListDf;
            ischools.desTimeTable = ListDf1;
            ViewBag.cClass = db.TCLassRow.Where(t => t.SchoolID == id).Sum(t => t.CLass);
            ViewBag.cStud = db.TCLassRow.Where(t => t.SchoolID == id).Sum(t => t.pupil);
            ischools.Tsubjects = db.TSubject.ToList();
            ischools.reducedTypes = db.ReducedTypes.ToList();
            string text = DateTime.Now.ToString("yyyy -MMMM -dd", cultures);


            return View(ischools);
        }

        public JsonResult EditT(string id, string id1, int sp, int rd)
        {
            if (id != null && sp.ToString() != null && rd.ToString() != null)
            {
                fun.fireSQL("UPDATE TImployees SET addClasses = " + sp + " , addSubClasses = " + rd + " WHERE [Identity] = '" + id + "'");
            }

            return Json(null);
        }

        public IActionResult printTeach(string id)
        {
            if (id != null)
            {

                var header = Path.GetFileName("~/static/headerSchoolEmpwork.html");
                var footer = Path.GetFileName("~/static/footer.html");
                string customSwitches = string.Format("--header-html  \"{0}\" " +
                            "--header-spacing \"8\" " +
                            "--header-font-name \"Open Sans\" " +
                            "--footer-font-size \"8\" " +
                            "--footer-font-name \"Open Sans\" " +
                            "--header-font-size \"10\" " +
                            //"--footer-right \"Pag: [page] de [toPage]\""+
                            "--footer-html  \"{1}\" ", header, footer);


                //var pdf = new ViewAsPdf("Reportempwork1", dt)
                //{

                //    CustomSwitches = customSwitches,

                //    PageMargins = new Rotativa.AspNetCore.Options.Margins(40, 10, 15, 10),
                //    PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape,
                //    PageSize = Rotativa.AspNetCore.Options.Size.A4
                //};


            //    return new ActionAsPdf(
            //        "ShowTable",
            //        new { id = id })
            //    {
            //        PageMargins = new Rotativa.AspNetCore.Options.Margins(10, 2, 2, 10),
            //        PageSize = Rotativa.AspNetCore.Options.Size.A3,
            //        PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape,

            //        FileName = "الجدول العام.pdf"
            //    };

            }

            return View();
        }


        public ActionResult TimeTable(int id)
        {
            if (id == null)
            {
                //     return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TSchools tSchools = db.TSchools.Find(id);
            if (tSchools == null)
            {
                return NotFound();
            }


            return View(tSchools);
        }
        public ActionResult Create(int id)
        {

            TimeTableView timeTable = new TimeTableView();
            timeTable.vMethods = Populatevm();

            ViewBag.id = id;
            return View(timeTable);
        }

        private static List<SelectListItem> Populatevm()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            string constr = "";// ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                string query = " SELECT id, viewName FROM viewMethod";
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    //using (SqlDataReader sdr = cmd.ExecuteReader())
                    //{
                    //    while (sdr.Read())
                    //    {
                    //        items.Add(new SelectListItem
                    //        {
                    //            Text = sdr["viewName"].ToString(),
                    //            Value = sdr["id"].ToString()
                    //        });
                    //    }
                    //}
                    con.Close();
                }
            }

            return items;
        }



        public void BulkInsert(DataTable dt)
        {

            string cs = "";// ConfigurationManager.ConnectionStrings["ConnMada"].ConnectionString;
            SqlConnection cn = new SqlConnection(cs);
            cn.Open();

            SqlBulkCopy bulkCopy = new SqlBulkCopy(cn);
            bulkCopy.DestinationTableName = "dbo.periods";
            DataTableReader reader = dt.CreateDataReader();
            bulkCopy.WriteToServer(reader);
            cn.Close();

        }


        public int sumTrue(day_s day1)
        {
            int st = Convert.ToInt32(day1.Saturday);
            int su = Convert.ToInt32(day1.Sunday);
            int mo = Convert.ToInt32(day1.Monday);
            int tu = Convert.ToInt32(day1.Tuesday);
            int we = Convert.ToInt32(day1.Wednesday);
            int th = Convert.ToInt32(day1.Thursday);
            int fr = Convert.ToInt32(day1.Friday);

            int total = st + su + mo + tu + we + th + fr;
            return total;
        }

        public ArrayList rand(int nm)
        {

            ArrayList num = new ArrayList();
            for (int i = 1; i <= nm; i++)
            {
                num.Add(i);

            }
            return num;

        }




        public ActionResult CreateM(Models.ModeView.TimeTableView timeTableView)
        {
            DataTable dt = new DataTable();
            //creating columns for DataTable  
            dt.Columns.Add(new DataColumn("id", typeof(int)));
            dt.Columns.Add(new DataColumn("T_id", typeof(int)));
            dt.Columns.Add(new DataColumn("day_id", typeof(int)));
            dt.Columns.Add(new DataColumn("period_id", typeof(int)));

qortuba/Views/TimeTable/CreateD.cshtml
@model qortuba.Models.ModeView.TimeTableView
@{
    ViewBag.Title = "DynamicTimeTable";
    Layout = "~/Views/Shared/_LayoutTable.cshtml";
   // Layout = "~/Views/Shared/_Layout1.cshtml";
}

<div class="titleBody" style="width:1000px;margin-left:auto;margin-right:auto;">
    <label class="lbl-nav"><a href="~/TimeTable/Index">الجداول</a> >  جدول آلى</label>

</div>
<style>
    .table td, th, thead {
        border: solid 2px;
    }

    thead {
        background-color: #e8d782;
    }

    tbody th {
        background-color: #fdfbf5;
    }

    col {
        background-color: #fff;
    }

    h5 {
        font-weight: bold;
    }
</style>

<table class="table" id="table1">
    <thead>
        <tr>
            <th>الفصول</th>

            @if (Model.day_S.Friday == true)
            {
                <th colspan="@Model.timeTable.per_num">الجمعة</th>}
            @if (Model.day_S.Saturday == true)
            {
                <th colspan="@Model.timeTable.per_num">السبت</th>}
            @if (Model.day_S.Sunday == true)
            {
                <th colspan="@Model.timeTable.per_num">الاحد</th>}
            @if (Model.day_S.Monday == true)
            {
                <th colspan="@Model.timeTable.per_num">الاثنين</th>}
            @if (Model.day_S.Tuesday == true)
            {
                <th colspan="@Model.timeTable.per_num">الثلاثاء</th>}
            @if (Model.day_S.Wednesday == true)
            {
                <th colspan="@Model.timeTable.per_num">الاربعاء</th>}
            @if (Model.day_S.Thursday == true)
            {
                <th colspan="@Model.timeTable.per_num">الخميس</th>}

        </tr>

    </thead>
    <colgroup>


        @for (int y = 0; y <= Model.periods.Where(t => t.T_id == Model.timeTable.id).Count(); y++)
        {

            <col />
        }

    </colgroup>
    <tbody>

        <tr>
            <th></th>
            @for (int i = 1; i <= ViewBag.days; i++)
            {
                for (int y = 1; y <= @Model.timeTable.per_num; y++)
                {

                    <th>
                        @y
                    </th>

                }
            }
        </tr>

        @foreach (var cl in ViewBag.classes)
        {

            <tr>
                <th>@cl</th>
                @foreach (var pr in Model.periods.Where(t => t.class_id == cl && t.T_id == Model.timeTable.id).ToList())
                {
                    var emp = ""; var subj = "";
                    if (pr.emp_id != null)
                    {
                        emp = Model.tImployees.Where(t => t.Identity == pr.emp_id.ToString()).SingleOrDefault().name1.ToString();
                    }
                    if (pr.subject_id != null)
                    {
                        subj = Model.tSubject.Where(t => t.SubID == pr.subject_id).SingleOrDefault().Subject.ToString();
                    }
                    <td><div id="@pr.subject_id"><a id="@pr.period_id"></a><span id="@pr.class_id"></span><h5 id="@pr.id">@subj </h5></div><div id="@pr.emp_id"><h5>@emp</h5></div></td>

                }
            </tr>
        }

    </tbody>

</table>

<div id="subject1" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">إضافة</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group row ">
                    @Html.Label("","المادة", htmlAttributes: new { @class = "col-sm-3 col-form-label" })
                    <div class="col-sm-9">
                        @Html.DropDownList("subject", null, "--من فضلك اختار--", htmlAttributes: new { @class = "form-control", @style = "padding:0px 0px;" })

                    </div>
                </div>
                <div class="form-group row ">
                    @Html.Label("","المعلم", htmlAttributes: new { @class = "col-sm-3 col-form-label" })
                    <div class="col-sm-9">
                        @Html.DropDownList("teacher", null, "--من فضلك اختار--", htmlAttributes: new { @class = "form-control", @style = "padding:0px 0px;" })

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="save" class="btn btn-primary">إضافة</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">اغلاق</button>
                <button type="button" id="del" class="btn btn-danger">حذف</button>
            </div>
        </div>
    </div>
</div>

@*Error Model*@
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal error-->
        <div class="modal-content">
            @*<div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">عذراً</h4>
                </div>*@
            <div class="modal-body" style="padding: 9px;">
                <div class="alert alert-danger" role="alert" id="error" style="margin-bottom: 0px; ">

                </div>
            </div>
            <div class="modal-footer" style=" margin-top: 0px;">
                <button type="button" class="btn btn-default" data-dismiss="modal">اغلاق</button>
            </div>
        </div>

    </div>
</div>
@section scripts{
    <script>
        loadT();
        colr();
    var event;
    var pr1;
    var cls;
    var id;
        $('table td').on("click", function (e) {
            event = e;
                id = $(this).find("div:first-child").find("h5").attr('id');
            var sj = $(this).find("div:first-child").attr('id');
            var tch = $(this).find("div:nth-child(2)").attr('id');
             pr1 = $(this).find("div:first-child").find("a").attr('id');
             cls = $(this).find("div:first-child").find("span").attr('id');

            $("#subject").val(sj);
            $("#teacher").val(tch);
            $("#subject1").modal('show');


        });
        $('#save').on("click", function () {


            var tid = parseInt(@Model.timeTable.id);
            var target = $(event.target);
            var ss = $('#subject option:selected').text();
            var ss1 = $('#teacher option:selected').text();
            if (ss == '--من فضلك اختار--') { alert('يجب اختيار المادة');  return }
            if (ss1 == '--من فضلك اختار--') { alert('يجب اختيار المعلم'); return }
       //   var period = target.index();
            var days = parseInt(@ViewBag.days);
       //   var class1 = Math.ceil(period / days);
            var subj = $('#subject option:selected').val();
            var teach = $('#teacher option:selected').val();
            var Tnu = @Model.timeTable.per_num * days;
            var TRow = parseInt(@ViewBag.countR);


            $("#subject1").modal('hide');
            $('#subject').val(0);
            $('#teacher').val(0);
            var periods = {
                id : id,
                T_id: tid,
                day_id: days,
                period_id: pr1,
                class_id: cls,
                subject_id: subj,
                emp_id: teach,
                Tnum: Tnu,
                Trow: TRow,
            }
            $.ajax({
                url: "/TimeTable/InsertP",
                type: "POST",
                data: periods,

                success: function (data) {
                    var tgName = target[0].nodeName;
                    if (tgName == 'TD') {
                        target.html("");
                        var idp = data['id'];
                        target.html("<div id=" + subj + "><a id=" + pr1 + "></a><span id=" + cls + "></span><h5 id=" + idp + ">" + ss + "</h5></div><div id=" + teach + "><h5>" + ss1 + "</h5></div>");

                    }
                    if (tgName == 'H5') {

                       // target.parent().parent().html("");
                        var dd = target[0].nodeName;
                        var idp = data['id'];
                        target.parent().parent().html("<div id=" + subj + "><a id=" + pr1 + "></a><span id=" + cls + "></span><h5 id=" + idp + ">" + ss + "</h5></div><div id=" + teach + "><h5>" + ss1 + "</h5></div>");

                    }

                },
                error: function () {
                    $("#error").html("مشكلة فى الحفظ");
                    $("#myModal").modal('show');


                }
            });
        });

           // delete row
         $('#del').on("click", function () {
            var tid = parseInt(@Model.timeTable.id);
            var target = $(event.target);
            var ss = $('#subject option:selected').text();
            var ss1 = $('#teacher option:selected').text();
            if (ss == '--من فضلك اختار--') { alert('يجب اختيار المادة'); return }
            if (ss1 == '--من فضلك اختار--') { alert('يجب اختيار المعلم'); return }
       //   var period = target.index();
            var days = parseInt(@ViewBag.days);
       //   var class1 = Math.ceil(period / days);
            var subj = $('#subject option:selected').val();
            var teach = $('#teacher option:selected').val();
            var Tnu = @Model.timeTable.per_num * days;
            var TRow = parseInt(@ViewBag.countR);


            $("#subject1").modal('hide');
            $('#subject').val(0);
            $('#teacher').val(0);
            var periods = {
                id : id,
                T_id: tid,
                day_id: days,
                period_id: pr1,
                class_id: cls,
                subject_id: subj,
                emp_id: teach,
                Tnum: Tnu,
                Trow: TRow,
            }
            $.ajax({
                url: "/TimeTable/DeleteM",
                type: "POST",
                data: periods,

                success: function (data) {
                    var tgName = target[0].nodeName;
                    if (tgName == 'TD') {
                        target.html("");
                        var idp = data['id'];
                        target.html("<div id=" + subj + "><a id=" + pr1 + "></a><span id=" + cls + "></span><h5 id=" + idp + "></h5></div><div id=" + teach + "><h5></h5></div>");
                        loadT();
                    }
                    if (tgName == 'H5') {

                       // target.parent().parent().html("");
                        var dd = target[0].nodeName;
                        var idp = data['id'];
                        target.parent().parent().html("<div id=" + subj + "><a id=" + pr1 + "></a><span id=" + cls + "></span><h5 id=" + idp + "></h5></div><div id=" + teach + "><h5></h5></div>");

                    }

                },
                error: function () {
                    $("#error").html("مشكلة فى الحفظ");
                    $("#myModal").modal('show');


                }
            });
        });

        // style table width
        function loadT() {
            var wd = $('#table1').width();
            $('#content1').width(wd);


        }

        function colr() {

            var cells = document.getElementsByTagName('col'),
                colors = ['ffffff', '#e8eef3', 'e6cfd5', 'cfe6e4', 'cfe6d6', 'd3f18a', 'd1d5e4'];

            for (var i = 0; i < cells.length; i++) {
                cells[i].style.backgroundColor = '#' + colors[Math.floor(Math.random() * colors.length)];
            }
        }

    </script>
}

qortuba/Views/TimeTable/PrintPage.cshtml
@{
    ViewBag.Title = "ShowTables";
    Layout = "~/Views/Shared/_Layout1.cshtml";

}

<div class="titleBody">
    <label class="lbl-nav"><a href="~/TimeTable/Index">طباعة جدول</a> </label>

</div>
<style type="text/css">
    .col-sm-5, .col-sm-7 {
        padding-right: 0px;
    }

    .form-control {
        padding: 2px 8px;
        font-weight: 600;
    }

    label {
        color: #39653a;
    }

    .fright {
        float: right;
    }

    #id {
        width: 70px;
    }
</style>

<div class="form-inline ">

    @using (Html.BeginForm("PrintPageTable", "TimeTable", new { }, FormMethod.Post,true, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-group row col-sm-4 ">
            @Html.Label("", "كود المدرسة", htmlAttributes: new { @class = "col-sm-4 col-form-label" })
            <div class="col-sm-6">
                @Html.Editor("id", new { htmlAttributes = new {@type = "number", @class = "form-control", @style = "width:200px;" } })
                
            </div>
        </div>

        <button type="submit" id="sub1" value="sub1" class="btn btn-success">طباعة / استخراج</button>
       
    }

</div>

qortuba/Views/TimeTable/TeachReport.cshtml
@{
    ViewBag.Title = "ShowTables";
    Layout = "~/Views/Shared/_Layout1.cshtml";

}

<div class="titleBody">
    <label class="lbl-nav"><a href="~/TimeTable/Index">طباعة جدول معلم</a> </label>

</div>
<style type="text/css">
    .col-sm-5, .col-sm-7 {
        padding-right: 0px;
    }

    .form-control {
        padding: 2px 8px;
        font-weight: 600;
    }

    label {
        color: #39653a;
    }

    .fright {
        float: right;
    }

    #id {
        width: 70px;
    }
</style>

<div class="form-inline ">

    @using (Html.BeginForm("showTeachReport", "TimeTable", new { }, FormMethod.Post,true, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-group row col-sm-4 ">
            @Html.Label("","كود المعلم", htmlAttributes: new { @class = "col-sm-4 col-form-label" })
            <div class="col-sm-6">
                @Html.Editor("id", new { htmlAttributes = new { @type = "number", @class = "form-control", @style = "width:200px;" } })

            </div>
        </div>

        <button type="submit" id="sub1" value="sub1" class="btn btn-warning">طباعة / استخراج</button>

    }

</div>

qortuba/Views/TimeTable/TimeTable.cshtml
@model qortuba.Models.TSchools
@{
    ViewBag.Title = "TimeTable";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<div class="titleBody">
    <label>الجداول</label>

</div>

<div class="form-inline">
    <div class="form-group row col-md-4">
        @Html.Label("","كود المدرسة", htmlAttributes: new { @class = "col-md-5 col-form-label" })
        <div class="col-md-9">
            @Html.EditorFor(model => model.SchoolID, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>
    </div>
    <div class="form-group row col-md-4">
        @Html.Label("", "اسم المدرسة", htmlAttributes: new { @class = "col-md-5 col-form-label" })
        <div class="col-md-9">
            @Html.EditorFor(model => model.School, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>
    </div>
    <div class="form-group row col-md-4">
        @Html.Label("", "الدائرة التعليمية", htmlAttributes: new { @class = "col-md-5 col-form-label" })
        <div class="col-md-9">
            @Html.EditorFor(model => model.circleAll, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>
    </div>
    <div class="form-group row col-md-4">
        @Html.Label("", "المستوى", htmlAttributes: new { @class = "col-md-5 col-form-label" })
        <div class="col-md-9">
            @Html.EditorFor(model => model.TLevel.NameLevel, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>
    </div>
    <div class="form-group row col-md-4">
        @Html.Label("", "التعليم", htmlAttributes: new { @class = "col-md-5 col-form-label" })
        <div class="col-md-9">
            @Html.EditorFor(model => model.Tuition1.Tuition1, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>
    </div>
    <div class="form-group row col-md-4">
        @Html.Label("", "النوع", htmlAttributes: new { @class = "col-md-5 col-form-label" })
        <div class="col-md-9">
            @Html.EditorFor(model => model.TSchoolsType.SchoolsType, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>
    </div>
</div>
<div class="form-group">
    <p>
        @Html.ActionLink("انشاء جدول", "Create" , new { id = Model.SchoolID }, new { @class = "btn btn-warning" })
    </p>
</div>