qortuba/Models/QortubaModel/adela.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qortuba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adela
    {
        public int id { get; set; }
        public string adName { get; set; }
        public string adFile { get; set; }
        public Nullable<int> adServ { get; set; }
    }
}

qortuba/Controllers/AdelaController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using qortuba.Data;
using qortuba.Models;

namespace qortuba.Controllers
{
    public class AdelaController : Controller
    {
       private readonly ApplicationDbContext db;
        public AdelaController(ApplicationDbContext applicationDbContext)
        {
            db = applicationDbContext;
        }
        private string[] ex = { ".pdf", ".doc", ".docx", ".xls", ".xlsx"};
        // GET: Adela
                public ActionResult Index()
        {
            var ad = db.adela;
            return View(ad);
        }

        // create emp
        public ActionResult Create(int id)
        {
            ViewBag.type = id;
            return View();
        }
        [HttpPost]
        // create emp add
        public ActionResult CreateEmp(adela adela, IFormFile AddFile)
        {
            string addfile1 = "";
            if (ModelState.IsValid)
            {
                if (AddFile != null && AddFile.Length > 0)
                {
                    string extension = Path.GetExtension(AddFile.FileName);
                    bool a = Array.Exists(ex, element => element == extension);
                    long sz = AddFile.Length;
                    adela ad = new adela();
                    ad.adName = adela.adName;
                    ad.adServ = adela.adServ;
                    ad.adFile = extension;
                    db.adela.Add(ad);
                    db.SaveChanges();
                    
                    if (a == true && sz <= 16777216)
                    {
                        if (!Directory.Exists(Path.GetDirectoryName("~/Upload/Emp")))
                        {

                            Directory.CreateDirectory(Path.GetFileName("~/Upload/Emp"));
                            var FullPath = Path.Combine(Path.GetFileName("~/Upload/Emp/"+ ad.id + extension));
                            addfile1 = adela.id + extension;
                            using (var fileSteam = new FileStream(FullPath, FileMode.Create))
                            {
                                AddFile.CopyToAsync(fileSteam);
                            }
                        }
                        else
                        {

                            var FullPath = Path.Combine(Path.GetFileName("~/Upload/Emp/"+ ad.id + extension));
                            addfile1 = adela.id + extension;
                            using (var fileSteam = new FileStream(FullPath, FileMode.Create))
                            {
                                AddFile.CopyToAsync(fileSteam);
                            }
                        }
                    }

                }

                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.error = "الرجاء مراجعة البيانات";
                return RedirectToAction("Create",new {id = adela.adServ });
            }
     
        }

        // edit emp
        public ActionResult EditEmp(int id)
        {

            var dd = db.adela.Where(p=>p.id == id).FirstOrDefault();

            ViewBag.type = dd.adServ;
            return View(dd);
        }
        [HttpPost]
        // edit emp 
        public ActionResult EditEmp(adela adela, IFormFile AddFile)
        {
            string addfile1 = "";
            if (ModelState.IsValid)
            {
                if (AddFile != null && AddFile.Length > 0)
                {
                    string extension = Path.GetExtension(AddFile.FileName);
                    bool a = Array.Exists(ex, element => element == extension);
                    long sz = AddFile.Length;
                    adela ad = db.adela.Where(p=>p.id == adela.id).FirstOrDefault();
                    string oex = ad.adFile;
                    ad.adName = adela.adName;
                    ad.adServ = adela.adServ;
                    ad.adFile = extension;
                    db.Entry(ad).State = EntityState.Modified;
                    db.SaveChanges();
                    if (a == true && sz <= 16777216)
                    {
                        if (!Directory.Exists(Path.GetFileName("~/Upload/Emp")))
                        {
                            var FullPathd = Path.Combine(Path.GetFileName("~/Upload/Emp/" + adela.id + oex));
                            if (System.IO.File.Exists(FullPathd))
                            {
                                System.IO.File.Delete(FullPathd);
                            }

                            Directory.CreateDirectory(Path.GetFileName("~/Upload/Emp"));
                            var FullPath = Path.Combine(Path.GetFileName("~/Upload/Emp/" + adela.id + extension));
                            addfile1 = adela.id + extension;
                            using (var fileSteam = new FileStream(FullPath, FileMode.Create))
                            {
                                AddFile.CopyToAsync(fileSteam);
                            }
                        }
                        else
                        {
                            var FullPathd = Path.Combine(Path.GetFileName("~/Upload/Emp/" + adela.id + oex));
                            if (System.IO.File.Exists(FullPathd))
                            {
                                System.IO.File.Delete(FullPathd);
                            }

                            var FullPath = Path.Combine(Path.GetFileName("~/Upload/Emp/" + adela.id + extension));
                            addfile1 = adela.id + extension;
                            using (var fileSteam = new FileStream(FullPath, FileMode.Create))
                            {
                                AddFile.CopyToAsync(fileSteam);
                            }
                        }
                    }

                }
                else
                {
                    adela ad = db.adela.Where(p => p.id == adela.id).FirstOrDefault();
                    ad.adName = adela.adName;
                    ad.adServ = adela.adServ;
                    db.Entry(ad).State = EntityState.Modified;
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.error = "الرجاء مراجعة البيانات";
                return View();
            }
        }

        // delete emp 
        public ActionResult DeleteEmp(int id)
        {
            if (id > 0)
            {

                var dd = db.adela.Where(p=>p.id == id).FirstOrDefault();
                if (dd != null)
                {
                    var FullPathd = Path.Combine(Path.GetFileName("~/Upload/Emp/" + dd.id + dd.adFile));
                    if (System.IO.File.Exists(FullPathd))
                    {
                        System.IO.File.Delete(FullPathd);
                    }
                    db.adela.Remove(dd);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            return RedirectToAction("Index");
        }


 

    }
}

qortuba/Views/Adela/Create.cshtml
@model qortuba.Models.adela

@{
    ViewBag.Title = "إضافة دليل";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<div class="titleBody">
    <label class="lbl-nav"><a href="~/adela/Index">الادلة</a> >إضافة دليل </label>

</div>

<label class="text-danger">@ViewBag.error</label>
@using (Html.BeginForm("CreateEmp", "Adela", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    if (ViewBag.type == 1)
    {
        <div class="panel panel-primary ">
            <div class="panel-heading">إضافة دليل موظف</div>
            <div class="panel-body">
                <div class="form-group">
                    @Html.Label("اسم الدليل","", htmlAttributes: new { })
                    <div>
                        @Html.EditorFor(model => model.adName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.ValidationMessageFor(model => model.adName, "", new { @class = "text-danger" })
                        <input type="hidden" id="adServ" name="adServ" value="@ViewBag.type" />

                    </div>

                </div>

                <div class="form-group">
                    @Html.Label("الملف", "", htmlAttributes: new { })
                    <div>
                        <input id="AddFile" name="AddFile" type="file" class="form-control" required style="display:inline-block;" />
                        <img src="~/images/pdf.png" width="60" height="30" />
                        <img src="~/images/word.jpg" width="30" height="30" />
                        <img src="~/images/excel.jpg" width="40" height="30" />
                    </div>

                </div>

                <div class="form-inline">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="إضافة" class="btn btn-success" />
                        @Html.ActionLink("عودة", "Index", null, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>
    }
    else if (ViewBag.type == 2)
    {
        <div class="panel panel-warning ">
            <div class="panel-heading">  إضافة دليل مدارس</div>
            <div class="panel-body">
                <div class="form-group">
                    @Html.Label("اسم الدليل","", htmlAttributes: new { })
                    <div>
                        @Html.EditorFor(model => model.adName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.ValidationMessageFor(model => model.adName, "", new { @class = "text-danger" })
                        <input type="hidden" id="adServ" name="adServ" value="@ViewBag.type" />
                    </div>

                </div>

                <div class="form-group">
                    @Html.Label("الملف", "", htmlAttributes: new { })
                    <div>
                        
                        <input id="AddFile" name="AddFile" type="file" class="form-control" required style="display:inline-block;" />
                        <img src="~/images/pdf.png" width="60" height="30" />
                        <img src="~/images/word.jpg" width="30" height="30" />
                        <img src="~/images/excel.jpg" width="40" height="30" />
                    </div>

                </div>

                <div class="form-inline">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="إضافة" class="btn btn-warning" />
                        @Html.ActionLink("عودة", "Index", null, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>
    }
    else if (ViewBag.type == 3)
    {
        <div class="panel panel-default ">
            <div class="panel-heading">إضافة دليل جداول</div>
            <div class="panel-body">
                <div class="form-group">
                    @Html.Label("اسم الدليل", "", htmlAttributes: new { })
                    <div>
                        @Html.EditorFor(model => model.adName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.ValidationMessageFor(model => model.adName, "", new { @class = "text-danger" })
                        <input type="hidden" id="adServ" name="adServ" value="@ViewBag.type" />
                    </div>

                </div>

                <div class="form-group">
                    @Html.Label("الملف", "", htmlAttributes: new { })
                    <div>
                        <input id="AddFile" name="AddFile" type="file" class="form-control" required style="display:inline-block;" />
                        <img src="~/images/pdf.png" width="60" height="30" />
                        <img src="~/images/word.jpg" width="30" height="30" />
                        <img src="~/images/excel.jpg" width="40" height="30" />
                    </div>

                </div>

                <div class="form-inline">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="إضافة" class="btn btn-default" />
                        @Html.ActionLink("عودة", "Index", null, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>
    }

    else if (ViewBag.type == 4)
    {
        <div class="panel panel-info  ">
            <div class="panel-heading">إضافة دليل ندب</div>
            <div class="panel-body">
                <div class="form-group">
                    @Html.Label("اسم الدليل", "", htmlAttributes: new { })
                    <div>
                        @Html.EditorFor(model => model.adName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.ValidationMessageFor(model => model.adName, "", new { @class = "text-danger" })
                        <input type="hidden" id="adServ" name="adServ" value="@ViewBag.type" />
                    </div>

                </div>

                <div class="form-group">
                    @Html.Label("الملف", "", htmlAttributes: new { })
                    <div>
                        <input id="AddFile" name="AddFile" type="file" class="form-control" required style="display:inline-block;" />
                        <img src="~/images/pdf.png" width="60" height="30" />
                        <img src="~/images/word.jpg" width="30" height="30" />
                        <img src="~/images/excel.jpg" width="40" height="30" />
                    </div>

                </div>

                <div class="form-inline">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="إضافة" class="btn btn-info" />
                        @Html.ActionLink("عودة", "Index", null, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>
    }

    else if (ViewBag.type == 5)
    {
        <div class="panel panel-primary ">
            <div class="panel-heading">إضافة دليل انصبة</div>
            <div class="panel-body">
                <div class="form-group">
                    @Html.Label("اسم الدليل", "", htmlAttributes: new { })
                    <div>
                        @Html.EditorFor(model => model.adName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.ValidationMessageFor(model => model.adName, "", new { @class = "text-danger" })
                        <input type="hidden" id="adServ" name="adServ" value="@ViewBag.type" />
                    </div>

                </div>

                <div class="form-group">
                    @Html.Label("الملف", "", htmlAttributes: new { })
                    <div>
                        <input id="AddFile" name="AddFile" type="file" class="form-control" required style="display:inline-block;" />
                        <img src="~/images/pdf.png" width="60" height="30" />
                        <img src="~/images/word.jpg" width="30" height="30" />
                        <img src="~/images/excel.jpg" width="40" height="30" />
                    </div>

                </div>

                <div class="form-inline">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="إضافة" class="btn btn-success" />
                        @Html.ActionLink("عودة", "Index", null, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>
    }

    else if (ViewBag.type == 6)
    {
        <div class="panel panel-success ">
            <div class="panel-heading">   إضافة دليل قبول</div>
            <div class="panel-body">
                <div class="form-group">
                    @Html.Label("اسم الدليل", "", htmlAttributes: new { })
                    <div>
                        @Html.EditorFor(model => model.adName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.ValidationMessageFor(model => model.adName, "", new { @class = "text-danger" })
                        <input type="hidden" id="adServ" name="adServ" value="@ViewBag.type" />
                    </div>

                </div>

                <div class="form-group">
                    @Html.Label("الملف", "", htmlAttributes: new { })
                    <div>
                        <input id="AddFile" name="AddFile" type="file" class="form-control" required style="display:inline-block;" />
                        <img src="~/images/pdf.png" width="60" height="30" />
                        <img src="~/images/word.jpg" width="30" height="30" />
                        <img src="~/images/excel.jpg" width="40" height="30" />
                    </div>

                </div>

                <div class="form-inline">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="إضافة" class="btn btn-success" />
                        @Html.ActionLink("عودة", "Index", null, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>
    }
}
@*Error Model*@

@section scripts{
    <script>
        $(function () {
            $('input[type=file]').change(function () {
                var val = $(this).val().toLowerCase(),
                    regex = new RegExp("(.*?)\.(pdf|doc|docx|xls|xlsx)$");

                if (!(regex.test(val))) {
                    $(this).val('');
                    alert('من فضلك يجب ان يكون امتداد الملف (pdf|doc|docx|xls|xlsx)');
                }
                if (this.files[0].size > 16777216) {
                    alert("يجب ان يكون حجم الملف اقل من 16 ميجا");
                }
            });
        });
    </script>
}

qortuba/Views/Adela/CreateEmp.cshtml
@model qortuba.Models.adela

@{
    ViewBag.Title = "إضافة دليل موظف";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<div class="titleBody">
    <label class="lbl-nav"><a href="~/adela/Index">الادلة</a> >إضافة دليل موظف</label>

</div>

<label class="text-danger">@ViewBag.error</label>
@using (Html.BeginForm("CreateEmp", "Adela", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    if (ViewBag.type == 1)
    {
        <div class="panel panel-primary ">
            <div class="panel-heading">إضافة دليل</div>
            <div class="panel-body">
                <div class="form-group">
                    @Html.Label("","اسم الدليل", htmlAttributes: new { })
                    <div>
                        @Html.EditorFor(model => model.adName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.ValidationMessageFor(model => model.adName, "", new { @class = "text-danger" })
                    </div>

                </div>

                <div class="form-group">
                    @Html.Label("","الملف", htmlAttributes: new { })
                    <div>
                        <input id="AddFile" name="AddFile" type="file" class="form-control" required style="display:inline-block;" />
                        <img src="~/images/pdf.png" width="60" height="30" />
                        <img src="~/images/word.jpg" width="30" height="30" />
                        <img src="~/images/excel.jpg" width="40" height="30" />
                    </div>

                </div>

                <div class="form-inline">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="إضافة" class="btn btn-success" />
                        @Html.ActionLink("عودة", "Index", null, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>
    }
    else if (ViewBag.type == 2)
    {
        <div class="panel panel-warning ">
            <div class="panel-heading">إضافة دليل</div>
            <div class="panel-body">
                <div class="form-group">
                    @Html.Label("","اسم الدليل", htmlAttributes: new { })
                    <div>
                        @Html.EditorFor(model => model.adName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.ValidationMessageFor(model => model.adName, "", new { @class = "text-danger" })
                    </div>

                </div>

                <div class="form-group">
                    @Html.Label("","الملف", htmlAttributes: new { })
                    <div>
                        <input id="AddFile" name="AddFile" type="file" class="form-control" required style="display:inline-block;" />
                        <img src="~/images/pdf.png" width="60" height="30" />
                        <img src="~/images/word.jpg" width="30" height="30" />
                        <img src="~/images/excel.jpg" width="40" height="30" />
                    </div>

                </div>

                <div class="form-inline">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="إضافة" class="btn btn-warning" />
                        @Html.ActionLink("عودة", "Index", null, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>
    }
    else if (ViewBag.type == 3)
    {
        <div class="panel panel-default ">
            <div class="panel-heading">إضافة دليل</div>
            <div class="panel-body">
                <div class="form-group">
                    @Html.Label("","اسم الدليل", htmlAttributes: new { })
                    <div>
                        @Html.EditorFor(model => model.adName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.ValidationMessageFor(model => model.adName, "", new { @class = "text-danger" })
                    </div>

                </div>

                <div class="form-group">
                    @Html.Label("","الملف", htmlAttributes: new { })
                    <div>
                        <input id="AddFile" name="AddFile" type="file" class="form-control" required style="display:inline-block;" />
                        <img src="~/images/pdf.png" width="60" height="30" />
                        <img src="~/images/word.jpg" width="30" height="30" />
                        <img src="~/images/excel.jpg" width="40" height="30" />
                    </div>

                </div>

                <div class="form-inline">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="إضافة" class="btn btn-default" />
                        @Html.ActionLink("عودة", "Index", null, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>
    }

    else if (ViewBag.type == 4)
    {
        <div class="panel panel-info  ">
            <div class="panel-heading">إضافة دليل</div>
            <div class="panel-body">
                <div class="form-group">
                    @Html.Label("","اسم الدليل", htmlAttributes: new { })
                    <div>
                        @Html.EditorFor(model => model.adName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.ValidationMessageFor(model => model.adName, "", new { @class = "text-danger" })
                    </div>

                </div>

                <div class="form-group">
                    @Html.Label("","الملف", htmlAttributes: new { })
                    <div>
                        <input id="AddFile" name="AddFile" type="file" class="form-control" required style="display:inline-block;" />
                        <img src="~/images/pdf.png" width="60" height="30" />
                        <img src="~/images/word.jpg" width="30" height="30" />
                        <img src="~/images/excel.jpg" width="40" height="30" />
                    </div>

                </div>

                <div class="form-inline">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="إضافة" class="btn btn-info" />
                        @Html.ActionLink("عودة", "Index", null, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>
    }

    else if (ViewBag.type == 5)
    {
        <div class="panel panel-primary ">
            <div class="panel-heading">إضافة دليل</div>
            <div class="panel-body">
                <div class="form-group">
                    @Html.Label("","اسم الدليل", htmlAttributes: new { })
                    <div>
                        @Html.EditorFor(model => model.adName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.ValidationMessageFor(model => model.adName, "", new { @class = "text-danger" })
                    </div>

                </div>

                <div class="form-group">
                    @Html.Label("","الملف", htmlAttributes: new { })
                    <div>
                        <input id="AddFile" name="AddFile" type="file" class="form-control" required style="display:inline-block;" />
                        <img src="~/images/pdf.png" width="60" height="30" />
                        <img src="~/images/word.jpg" width="30" height="30" />
                        <img src="~/images/excel.jpg" width="40" height="30" />
                    </div>

                </div>

                <div class="form-inline">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="إضافة" class="btn btn-success" />
                        @Html.ActionLink("عودة", "Index", null, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>
    }

    else if (ViewBag.type == 6)
    {
        <div class="panel panel-success ">
            <div class="panel-heading">إضافة دليل</div>
            <div class="panel-body">
                <div class="form-group">
                    @Html.Label("","اسم الدليل", htmlAttributes: new { })
                    <div>
                        @Html.EditorFor(model => model.adName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.ValidationMessageFor(model => model.adName, "", new { @class = "text-danger" })
                    </div>

                </div>

                <div class="form-group">
                    @Html.Label("","الملف", htmlAttributes: new { })
                    <div>
                        <input id="AddFile" name="AddFile" type="file" class="form-control" required style="display:inline-block;" />
                        <img src="~/images/pdf.png" width="60" height="30" />
                        <img src="~/images/word.jpg" width="30" height="30" />
                        <img src="~/images/excel.jpg" width="40" height="30" />
                    </div>

                </div>

                <div class="form-inline">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="إضافة" class="btn btn-success" />
                        @Html.ActionLink("عودة", "Index", null, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>
    }
}
@*Error Model*@

@section scripts{
    <script>
        $(function () {
            $('input[type=file]').change(function () {
                var val = $(this).val().toLowerCase(),
                    regex = new RegExp("(.*?)\.(pdf|doc|docx|xls|xlsx)$");

                if (!(regex.test(val))) {
                    $(this).val('');
                    alert('من فضلك يجب ان يكون امتداد الملف (pdf|doc|docx|xls|xlsx)');
                }
                if (this.files[0].size > 16777216) {
                    alert("يجب ان يكون حجم الملف اقل من 16 ميجا");
                }
            });
        });
    </script>
}